"""added projectsessions

Revision ID: 4d64f2ff2837
Revises: 7a5fe4720220
Create Date: 2023-12-18 10:07:55.177030

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d64f2ff2837'
down_revision = '7a5fe4720220'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('session_id', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['users.id'], name=op.f('fk_project_sessions_project_id_users')),
    sa.ForeignKeyConstraint(['session_id'], ['users.id'], name=op.f('fk_project_sessions_session_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_project_sessions'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('project_sessions')
    # ### end Alembic commands ###
