"""added projectsessions

Revision ID: 549235071aa2
Revises: 4d64f2ff2837
Create Date: 2023-12-18 10:13:03.283878

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '549235071aa2'
down_revision = '4d64f2ff2837'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project_sessions', schema=None) as batch_op:
        batch_op.drop_constraint('fk_project_sessions_session_id_users', type_='foreignkey')
        batch_op.drop_constraint('fk_project_sessions_project_id_users', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_project_sessions_session_id_sessions'), 'sessions', ['session_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_project_sessions_project_id_projects'), 'projects', ['project_id'], ['id'])

    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_constraint('fk_projects_session_id_sessions', type_='foreignkey')
        batch_op.drop_column('session_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('session_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('fk_projects_session_id_sessions', 'sessions', ['session_id'], ['id'])

    with op.batch_alter_table('project_sessions', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_project_sessions_project_id_projects'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_project_sessions_session_id_sessions'), type_='foreignkey')
        batch_op.create_foreign_key('fk_project_sessions_project_id_users', 'users', ['project_id'], ['id'])
        batch_op.create_foreign_key('fk_project_sessions_session_id_users', 'users', ['session_id'], ['id'])

    # ### end Alembic commands ###
