"""removed documentEditor

Revision ID: 7a5fe4720220
Revises: 28f7353b7221
Create Date: 2023-12-14 08:18:07.174658

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a5fe4720220'
down_revision = '28f7353b7221'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('document_editors')
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.alter_column('project_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_constraint('fk_documents_owner_id_users', type_='foreignkey')
        batch_op.drop_constraint('fk_documents_session_id_sessions', type_='foreignkey')
        batch_op.drop_column('session_id')
        batch_op.drop_column('owner_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('owner_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('session_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('fk_documents_session_id_sessions', 'sessions', ['session_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key('fk_documents_owner_id_users', 'users', ['owner_id'], ['id'], ondelete='SET NULL')
        batch_op.alter_column('project_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    op.create_table('document_editors',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('document_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('permission_level', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], name='fk_document_editors_document_id_documents'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_document_editors_user_id_users'),
    sa.PrimaryKeyConstraint('id', name='pk_document_editors')
    )
    # ### end Alembic commands ###
