"""modified session

Revision ID: dbefa2c3e30a
Revises: 67ee9d6f0216
Create Date: 2023-12-19 00:54:38.885136

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dbefa2c3e30a'
down_revision = '67ee9d6f0216'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.alter_column('language',
               existing_type=sa.VARCHAR(),
               nullable=False)

    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.drop_column('duration')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('duration', sa.VARCHAR(), autoincrement=False, nullable=True))

    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.alter_column('language',
               existing_type=sa.VARCHAR(),
               nullable=True)

    # ### end Alembic commands ###
